### ISSUE TITLE
Stuttering and artefacts after 45 seconds of iTunes video playback

### ISSUE THREAD

**Issue by zebuscat** [vit9696/Shiki#1]
Hi,
observed the following issues with Shiki 1.5.0 after I have updated my system to iTunes 12.4.2.4 and OS X 10.11.6.
Trailers in the iTunes Video section run flawless for about 45 seconds - after that I experience artefacts , stuttering and video freeze situations.
My previous config Mac OS X 10.11.5 , iTunes 12.4.1, Shiki 1.5.0 had no issues.

Cheers Dirk

**Comment by arminmacx** [comment]
Hi,

I have the same problem as zebuscat have. I think there should be minor update to code

**Comment by vit9696** [comment]
Read the FAQ before bothering me with the issues. That's not the bug of Shiki but iTunes. To fix that you need to reset DRM state. The FAQ properly describes how to do that.

**Comment by arminmacx** [comment]
nobody bothering you .it just happened suddnely so reported. why you so mean by BOTHERING ?

**Comment by zebuscat** [comment]
Thank you for your hard work and pointing us at the FAQ - your DRM cleanup procedure has solved my issue .
But I never saw this misbehaviour on any of my Apple machines ?!
Is it possible to add this cleanup procedure to the Shiki code ?

Cheers Dirk

**Comment by vit9696** [comment]
No, it is not possible for various reasons. From my own experience this happens only when you use iTunes once or more without Shiki before or after using Shiki. Therefore it should not happen under normal conditions (and I actually had it only once during the development). Deleting SC Info folder is usually enough, by the way, so the fix is pretty trivial after all.
