### ISSUE TITLE
AMD Vega H.265 decode/encode support on High Sierra?

### ISSUE THREAD

**Issue by oscarbg** [vit9696/Shiki#14]
Hi,
have a system with three GPUs Intel HD 530, Nvidia 970 and Radeon RX Vega 56..
have installed Shiki Lilu Intel,AMD and Nvidia graphic fixups kexts (WhateverGreen in AMD case)..

by disabling Intel IGPU in BIOS /AMD GPU with -radvesa and Nvidia GPU by uninstalling Nvidia Web drivers I can check each GPU individually..  Nvidia GPU Maxwell doesn't seem to have any video decode/encode support..

Intel IGPU was getting only h264 support initially but using your latest Shiki I get H265 support too..

for AMD RX Vega I'm getting only h264 support only i.e. both h265 decode/encode aren't working..
I check with latest FFmpeg using h264_videotoolbox and h265_videotoolbox encoders ( ffmpeg  -y -I  input.mp4  -c:v h264_videotoolbox ..)  
for decoding I use mpv --hwdec=videotoolbox with a HEVC file..

notice that for Intel IGPUs both work so both programs work with VideoToolbox correctly..
 
question is this:
I'm using 10.13.2 beta 17C69 as has much better Vega support than stable..

as RX Vega supports both decode/encode of H.265 streams it's a limitation of Apple AMD drivers or can be enable with a hack similar to how you enabled H265 in Intel SKL..
also it's important to use instead of Imac14,2 and iMac Pro id?

also in your FAQ you say High Sierra doesn't work with two GPUs correctly and I check that I can't get AMD+NV GPUs working simultaneously (having Nvidia web drivers) seems to crash at login.. I remember some years ago (a GTX 470 +AMD 5850) was working right on hackintosh of the time..
so maybe a matter of renaming some GPU to GFX0 the another one to GFX1 or something?
can you point to some ideas to test?

thanks..
sorry for large post!

**Comment by vit9696** [comment]
Morning…

As for HEVC support on AMD Vega, it should be possible by injecting the necessary properties into your driver and setting the right properties of AppleGVA configuration. See this [manual](https://applelife.ru/threads/h-265-hevc-high-efficiency-video-coding.2451376/) in the spoiler of the first message. It has never been tested on Vega though, only on Polaris, so there remains a chance for it not to function at least for now. To be honest, I would not recommend this with a HEVC-capable IGPU though.

As for multigpu support, I am afraid it does not matter much how you name them. Last time I tried I could not get 10.13 work with both nvidia and amd, one of the cards simply boot-looped and the other was constantly resetting the session at login. I guess this is what you also have.

As for your configuration, I would still probably suggest you totally remove your Maxwell GPU, change HD 530 to a connector-less frame and remove IntelGraphicsFixup and NvidiaGraphicsFixup. 

I suppose if you run into issues when following the guide you may better ask people on applelife, since I am not too involved there.
