### ISSUE TITLE
Hardware acceleration stops working after upgrade to 10.13.2

### ISSUE THREAD

**Issue by esetnik** [vit9696/Shiki#18]
VDADecoderChecker reporting no hardware acceleration after update to 10.13.2

```
❯ /Applications/VDADecoderChecker                                                                                                                                                                 
GVA info: Successfully connected to the Intel plugin, offline Gen95 
AVDCreateGPUAccelerator: Error loading GPU renderer
VDADecoderCreate failed. err: -12473
An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process.
VDADecoderCreate failed. err: -12473
```

Attached logs.
[shiki.log](https://github.com/vit9696/Shiki/files/1545216/shiki.log)

**Comment by vit9696** [comment]
Hi, I carefully checked the log and AppleGVA itself. Basically they both say that they worked just fine, the patches were found, and the AppleGVA code itself did not even change in that place.

What is slightly suspicious though, is that some patches are already applied, but I'd think it is normal due to the nature of the section usage.

Could you try with `-liluslow` or with a clean installation of 10.13.2 if any? If it still works, then Apple most likely broke something but that would require some debugging…

**Comment by esetnik** [comment]
Unfortunately still not working with `-liluslow`. Logs attached. 

[shiki.log](https://github.com/vit9696/Shiki/files/1546078/shiki.log)

**Comment by esetnik** [comment]
FWIW I also manually patched `AppleGVA.framework/Resources/Info.plist` to check whether this is caused by a failure of the Shiki `board-id` patch, but it still doesn't work even with a patched `forceBoostOff` flag for `iMac18,3`. I think this is not a regression of the issue we fixed previously.

**Comment by vit9696** [comment]
In this case one needs to debug AppleGVA.framework and find what broke in the current solution. Currently what Shiki does is replacing `0F 84 89 01 00 00 84 DB 0F 84 81 01 00 00` with 
`90 90 90 90 90 90 84 DB 90 90 90 90 90 90`. For some unknown reason it is no longer enough, though the function looks almost the same (well, frankly said there is a slight chance Shiki patch fails, so you may try to bin-patch and resign AppleGVA).

I don't see a way to quickly get it from a static analysis, so here one will need to do some debugging. Since I do not have the hardware, it is practically impossible for me to tell what is wrong. I guess it is somewhat possible if I have the remote-control over the problematic machine via vnc or stuff like TeamViewer, but that would require time to be found…

**Comment by esetnik** [comment]
I know you are a busy person, but I'd be happy to volunteer my hardware via remote debugging if that is of interest to you. I'd really like to help get this working because so many of us have this hardware configuration and will be upgrading to 10.13.2. I'm afraid my static analysis skills are probably not sufficient to debug this on my own, but it might be a good learning opportunity for me. And potentially helpful for me to be able to contribute further to the Shiki project / hackintosh community in the future. Let me know what you would like to do.

What is your hardware configuration? I'm considering switching from Nvidia 1080 TI to RX 580 because of separate issues https://www.tonymacx86.com/threads/gtx-1060-performance-on-10-13-high-sierra.236962.

**Comment by vit9696** [comment]
Could you mail me via iMessage (vit9696 at icloud dot com) or GTalk (same nickname at avp dot su)?
You could also find me at ext3 and freenode IRCs if that is more convenient.

**Comment by xelanaiznac** [comment]
@esetnik try doing a clean instal of 10.13.2
i have working vdachecker after upgrading from 10.13.1 to 10.13.2 using apple combo update (no App Store update).
even another user, pastry chef, had this issue and he solved it doing a clean install of 10.13.2

**Comment by esetnik** [comment]
This is an interesting development. The combo update / clean install of HS uses a different version of Nvidia web drivers (378.10.10.10.25.102) and also has a different build number (17C88). I wonder if something is broken in `25.103`.

**Comment by esetnik** [comment]
I just did a clean install of HS and using the identical hardware / clover configuration I get a pass from VDADecoderCheck in 17C88 and a fail in 17C89.

**Comment by xelanaiznac** [comment]
I have 17c89 with latest nvidia drivers and no issue with vdadecodercheck 

Inviato da iPhone

**Comment by esetnik** [comment]
So something different between the app store update and the combo update?

**Comment by xelanaiznac** [comment]
Yes, I think.
Even the user @pastrychef confirms everything working with clean install of 10.13.2
I confirm that 10.13.1 to 10.13.2 trough combo update, gives me 17c89 and VDADecoderChecker is fine

Inviato da iPhone

**Comment by esetnik** [comment]
Issue was solved by @vit9696. It turned out that I had a corrupted AppleGVA.framework. We replaced my corrupted version with a fresh copy from 10.13.2 and video acceleration is fully working.
