### ISSUE TITLE
Which bootflag?

### ISSUE THREAD

**Issue by Symphosize** [vit9696/Shiki#23]
My setup:
Motherboard: Gigabyte GA-Z170M-D3H
Processor: Intel i7 6700K 4.00Ghz
Video Card: GeForce GTX 970
Memory: 2 x 16GB Crucial Ballistix DDR4 2400
SSD: Samsung 960 EVO Series - 500GB NVMe - M.2

I have tried the following bootflags:
shikigva=12
 shikigva=60
 shikigva=48
 shikigva=18
 shikigva=4

And I have not been able to get VDADecoderChecker to be able to pass my system off yet. I can get to where MacX says I have Hardware Encoding Supported, but I am using a piece of software called Ecamm Live and it says "WARNING: Video Encoder is Busy - Another App is using the Mac hardware accelerated video encoder. This may affect Ecamm Live's ability to stream. Quit any other apps that may be encoding video." However I have closed all other apps. It seems that things are partially working, but I don't understand how to fully debug, and I don't understand the "x" portion of  shikigva=x where x=bitmask.

Can you offer any additional help on this?

**Comment by vit9696** [comment]
There exists a full description of every bit in shikigva flag, which you sum to make the resulting value:
https://github.com/vit9696/Shiki/blob/master/Shiki/kern_start.cpp#L18

Currently you need `shikigva=28` for 10.13. But in future releases you should not need shikigva at all, since automatic GPU detecting is being added. It will be mentioned in the changelog.

**Comment by Symphosize** [comment]
Ok I switched to `shikigva=28` but I am having all of the same issues. Any thoughts on that?

**Comment by vit9696** [comment]
https://applelife.ru/threads/zavod-intel-quick-sync-video.817923/

**Comment by Symphosize** [comment]
I'm sorry I don't understand it :(
